import os
import datetime
import logging
import smtplib
import requests
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")

def ensure_reports_dir():
    """Ensure the reports directory exists."""
    if not os.path.exists(REPORTS_DIR):
        os.makedirs(REPORTS_DIR)

def generate_markdown_report(analysis_text: str):
    """
    Saves the analysis output as a daily Markdown report file.
    Optionally, you could add logic here to email the file or send via Slack.
    """
    ensure_reports_dir()
    
    date_str = datetime.date.today().strftime("%Y-%m-%d")
    filename = f"Business_Implications_Report_{date_str}.md"
    file_path = os.path.join(REPORTS_DIR, filename)
    
    # We will prepend a title header
    report_content = f"# Daily Strategic Business & Tech Report\n*Date: {date_str}*\n\n"
    report_content += "## Executive Analysis\n\n"
    report_content += analysis_text
    report_content += "\n\n---\n*Report dynamically generated by Daily News Analyzer Agent.*"
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(report_content)
        
    logger.info(f"Successfully generated report at: {file_path}")
    
    # Trigger notifications if configured
    send_slack_notification(report_content)
    send_email_notification(date_str, report_content)
    
    return file_path

def send_slack_notification(content: str):
    """Sends the report to a Slack channel via Webhook URL."""
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        logger.debug("Slack Webhook URL not configured. Skipping Slack notification.")
        return
        
    logger.info("Sending report to Slack...")
    try:
        # We might want to truncate if content is too long for a single Slack message, 
        # but for simplicity we send it directly.
        payload = {"text": f"*Daily Business Report*\n\n{content}"[:3500]}
        response = requests.post(webhook_url, json=payload)
        response.raise_for_status()
        logger.info("Successfully sent Slack notification.")
    except Exception as e:
        logger.error(f"Failed to send Slack notification: {e}")

def send_email_notification(date_str: str, content: str):
    """Sends the report via Email using SMTP."""
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    
    if not all([sender, password, receiver]):
        logger.debug("Email credentials not fully configured. Skipping Email notification.")
        return
        
    logger.info(f"Sending Email report to {receiver}...")
    try:
        msg = MIMEMultipart()
        msg['From'] = sender
        msg['To'] = receiver
        msg['Subject'] = f"Daily Strategic Business Report - {date_str}"
        
        # We can send it just as text for now
        msg.attach(MIMEText(content, 'plain'))
        
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)
        server.quit()
        
        logger.info("Successfully sent Email notification.")
    except Exception as e:
        logger.error(f"Failed to send Email notification: {e}")


if __name__ == "__main__":
    generate_markdown_report("Mock analysis data from the test run.")
